pr:
- master

jobs:
  - job: linux
    variables:
      activate.command: "source activate"
    strategy:
      matrix:
        py37:
          python.version: "3.7"

    pool:
      vmImage: ubuntu-16.04

    steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - script: |
        conda env create -f environment.yml
      displayName: Create environment
    - script: | 
        source activate minimal-panel
        make test
      displayName: Run tests
